In [1]:
import numpy as np

In [4]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,0],[0,1]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[1 0]
 [0 1]]


#### np.vstack()  
행렬을 수직으로 결합(수직방향으로, vertical) 

In [5]:
C = np.vstack((A,B))
print(C)

[[1 2]
 [3 4]
 [1 0]
 [0 1]]


#### np.hstack()  
행렬을 수평으로 결합(수평방향으로, horizental) 

In [6]:
D = np.hstack((A,B))
print(D)

[[1 2 1 0]
 [3 4 0 1]]


#### np.column_stack()  
행렬을 열벡터 형태로 결합(column: 열(건물을 구성하는 기둥)) 

In [11]:
a = np.array(list(range(1,4))) # [1, 2, 3]
b = np.array(list(range(4,7))) # [4, 5, 6]
c = np.array(list(range(7,10))) # [7, 8, 9]

In [12]:
E1 = np.column_stack((a,b,c))
print(E2)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


#### np.row_stack()  
행렬을 행벡터 형태로 결합(row: 행) 

In [13]:
E2 = np.row_stack((a,b,c))
E

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### np.concatenate((합칠행렬1, 합칠행렬2), 방향(axis=))  
- axis = 0 : 열방향, 세로로 합치기
- axis = 1 : 행방향, 가로로 합치기

In [14]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,0],[0,1]])

In [17]:
C = np.concatenate((A,B), axis=0) # 세로로 합치기, 열방향
print(C)

[[1 2]
 [3 4]
 [1 0]
 [0 1]]


In [18]:
D = np.concatenate((A,B), axis=1) # 가로로 합치기, 행방향
print(D)

[[1 2 1 0]
 [3 4 0 1]]


## 배열 분할 함수
- 배열을 2개 이상의 배열로 나눌때 사용
- 행방향 분할(가로방향) : hsplit
- 열방향 분할(세로방향) : vsplit

#### hsplit : 행렬을 가로방향으로 나눔
- hsplit(분할할 행렬, 분할 개수)  
- hsplit(분할할 행렬, (기준점1, 기준점2, ...)  )

In [21]:
A = np.arange(1,13).reshape(2,6)
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [22]:
a = np.hsplit(A,3) # A행렬을 동일한 크기의 3개의 행렬로 가로 방향으로 자름

In [27]:
for i in a:
    print(i)
    print()

[[1 2]
 [7 8]]

[[ 3  4]
 [ 9 10]]

[[ 5  6]
 [11 12]]



In [30]:
b = np.hsplit(A,(2,5))

In [31]:
for i in b:
    print(i)
    print()

[[1 2]
 [7 8]]

[[ 3  4  5]
 [ 9 10 11]]

[[ 6]
 [12]]



#### vsplit : 행렬을 세로방향으로 나눔
- vsplit(분할할 행렬, 분할 개수)  
- vsplit(분할할 행렬, (기준점1, 기준점2, ...)  )

In [35]:
A = np.arange(10,130,10).reshape(6,2)
A

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100],
       [110, 120]])

In [36]:
a = np.vsplit(A,3)

In [37]:
for i in a:
    print(i)
    print()

[[10 20]
 [30 40]]

[[50 60]
 [70 80]]

[[ 90 100]
 [110 120]]



In [38]:
b = np.vsplit(A,(1,4))

In [39]:
for i in b:
    print(i)
    print()

[[10 20]]

[[30 40]
 [50 60]
 [70 80]]

[[ 90 100]
 [110 120]]



## 2.3 Indexing and Slicing
### 2.3.1 인덱싱
- 넘파이 배열은 파이썬의 리스트 처엄 인덱싱이 가능하며, for문을 사용하여 원소들을 하나씩 꺼내 올 수 있음

In [40]:
A = np.arange(0,15,2)
A

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [41]:
A.shape

(8,)

In [47]:
# for문을 사용하여 배열의 인덱스를 통해 원소에 접근 가능
for i in range(len(A)):
    print(f'A[{i}]: {A[i]}')

A[0]: 0
A[1]: 2
A[2]: 4
A[3]: 6
A[4]: 8
A[5]: 10
A[6]: 12
A[7]: 14


In [48]:
# for문을 사용하여 배열의 역인덱스를 통해 원소에 접근 가능
for i in range(len(A)):
    print(f'A[{-(i+1)}]: {A[-(i+1)]}')

A[-1]: 14
A[-2]: 12
A[-3]: 10
A[-4]: 8
A[-5]: 6
A[-6]: 4
A[-7]: 2
A[-8]: 0


#### 다차원 배열에 대한 접근
- 차원의 개수만큼 인덱스를 사용하여 개별 원소에 접근 가능

In [49]:
A = np.arange(1,13).reshape(3,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
height,width = A.shape
print(height,width)

3 4


In [57]:
for i in range(height):
    for j in range(width):
        print(f'A[{i},{j}]: {A[i,j]}')

A[0,0]: 1
A[0,1]: 2
A[0,2]: 3
A[0,3]: 4
A[1,0]: 5
A[1,1]: 6
A[1,2]: 7
A[1,3]: 8
A[2,0]: 9
A[2,1]: 10
A[2,2]: 11
A[2,3]: 12


### 전치 행렬(Transposed Matrix)
- 가로가 세로가 되고 세로가 가로가 되는 행렬
- (0,0),(1,1),(2,2) : 그래로
- (1,0) -> (0,1) : 가로 세로가 바뀜
- A.T 의 형태로 표현

In [76]:
A = np.arange(1,10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
#전치행렬
A = A.T
print(A)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [78]:
B = np.array([1,2,3])
for b in B:
    print(b)

1
2
3


#### 2차원 행렬은 for문을 사용하면 한 행의 값을 가져옴

In [83]:
A = np.arange(1,10).reshape(3,3)
for row_a in A:
    print(row_a)

[1 2 3]
[4 5 6]
[7 8 9]


#### 한개의 열을 가져오려면 행렬을 전치한 후 행을 가져오면 됨

In [84]:
A = np.arange(1,10).reshape(3,3)
for col_a in A.T:
    print(col_a)

[1 4 7]
[2 5 8]
[3 6 9]


#### 행렬의 개별 원소를 출력
- flat 사용

In [90]:
A = np.arange(1,10).reshape(3,3)
for a in A.flat:
    print(a)

1
2
3
4
5
6
7
8
9


## 2.4 얕은 복사 깊은 복사

### 대입
- 배열을 생성하여 변수에 대입한 다음 이변수를 다시 다른 변수에 대입하면, 하나의 넘파이배열을 가리키는 2개의 변수가 생김

In [92]:
a = np.arange(12) # [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]
b = a # 배열을 생성하여 변수에 대입한 다음 이변수를 다시 다른 변수에 대입

In [93]:
print(a==b)

[ True  True  True  True  True  True  True  True  True  True  True  True]


In [94]:
print(a is b)

True


#### 원소를 수정하면 서로 영향을 줌

In [95]:
a[0] = 100
print(a)
print(b)

[100   1   2   3   4   5   6   7   8   9  10  11]
[100   1   2   3   4   5   6   7   8   9  10  11]


#### shape변경해도 둘다 shape가 변경됨

In [96]:
b.shape = 3,4

In [97]:
print(a.shape)

(3, 4)


### 얕은 복사
- 얕은 복사를 하면 기본 배열의 원소를 공유하는 새로운 배열을 생성
- 새로 생성된 배열을 뷰라고 부름
- 원소를 공유하기때문에 한쪽배열을 수정하면 다른 배열의 데이터도 수정됨

In [98]:
a = np.arange(12)
b = a.view()

In [99]:
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [100]:
print(b.base is a)

True


In [101]:
print(a is b)

False


In [102]:
a[0] = 100
b[11]=100
print(a)
print(b)

[100   1   2   3   4   5   6   7   8   9  10 100]
[100   1   2   3   4   5   6   7   8   9  10 100]


In [105]:
# a의 사이즈를 바꾸어도 b의 사이즈는 변경되지 않는다
a.resize(3,4)
a

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 100]])

In [104]:
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100])

In [107]:
# 슬라이싱 한 데이터는 영향을 미침
a[0][2] = 500
print(a)
print(b)

[[100   1 500   3]
 [  4   5   6   7]
 [  8   9  10 100]]
[100   1 500   3   4   5   6   7   8   9  10 100]


In [108]:
c = a[0]
c[:]=0
print(a)
print(b)

[[  0   0   0   0]
 [  4   5   6   7]
 [  8   9  10 100]]
[  0   0   0   0   4   5   6   7   8   9  10 100]


### 깊은 복사
- 기존의 배열의 데이터를 공유하지 않는 복사본이 필요한 경우 사용
- copy메서드를 사용
- 기존 배열의 데이터를 공유하지 않고 새로운 메모리 공간에 데이터를 복사하여 사용

In [109]:
a = np.arange(12)
b = a.copy()

In [110]:
print(a==b)

[ True  True  True  True  True  True  True  True  True  True  True  True]


In [111]:
print(a is b)

False


In [112]:
a[0] = 100
print(a)
print(b)

[100   1   2   3   4   5   6   7   8   9  10  11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


## 크기가 같은 행렬의 연산

In [113]:
A = np.array([[2,4],[6,8]])
B = np.array([[2,2],[2,2]])

In [114]:
A

array([[2, 4],
       [6, 8]])

In [115]:
B

array([[2, 2],
       [2, 2]])

In [116]:
# 사칙연산  : 덧셈
A+B

array([[ 4,  6],
       [ 8, 10]])

In [117]:
# 사칙연산  : 뺄셈
A-B

array([[0, 2],
       [4, 6]])

In [118]:
# 사칙연산  : 곱셈
A*B

array([[ 4,  8],
       [12, 16]])

In [119]:
# 사칙연산  : 나눗셈
A/B

array([[1., 2.],
       [3., 4.]])

### 행렬처럼 연산
- np.dot(A,B)
- A.dot(B)
- python 3.5이상 : A@B

In [120]:
C = np.dot(A,B)
print(C)

[[12 12]
 [28 28]]


In [121]:
print(A.dot(B))
print(A@B)

[[12 12]
 [28 28]]
[[12 12]
 [28 28]]


## 크기가 다른 행렬의 연산
- 넘파이에서 계산의 효율성을 위해서 브로드캐스팅을 이용한 연산 지원
- 스칼라 또는 적은 차원 개수를 가진 배열을 많은 차원개수를 가진 배열의 크기와 동일하게 만든 후 연산을 진행
- 브로드 캐스팅이 가능해야 연산이 가능

In [123]:
A = np.arange(10,130,10).reshape(3,4)
print(A)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [124]:
B = np.arange(1,5)
print(B)

[1 2 3 4]


In [125]:
print(A+B)

[[ 11  22  33  44]
 [ 51  62  73  84]
 [ 91 102 113 124]]


In [127]:
A = np.arange(10,130,10).reshape(3,4)
B = np.arange(1,4)

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [129]:
print(A+B) #브로드캐스팅 안됨, 에러발생

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 